### ISSUE TITLE
Caffe make error

### ISSUE THREAD

**Issue by BAILOOL** [hszhao/PSPNet#18]
Getting the following error when compiling Caffe with `make`:

```
./include/caffe/common.cuh(9): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "/tmp/tmpxft_00003eec_00000000-5_domain_transform_layer.cpp4.ii".
```

Any solutions?

**Comment by dongzhuoyao** [comment]
http://stackoverflow.com/questions/39274472/error-function-atomicadddouble-double-has-already-been-defined

**Comment by BAILOOL** [comment]
@dongzhuoyao that worked for CUDA8 and Titax X Pascal. Thank you!
