### ISSUE TITLE
error: function "atomicAdd(double *, double)" has already been defined

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [hszhao/PSPNet#4]
hi @hszhao, after i do `cp Makefile.config.example Makefile.config`, and then `make -j9`, i met this problem: `./include/caffe/common.cuh(9): error: function "atomicAdd(double *, double)" has already been defined`. how to fix it? thanks.

**Comment by hszhao** [comment]
Hi, you can follow this link(http://stackoverflow.com/questions/39274472/error-function-atomicadddouble-double-has-already-been-defined) if using CUDA8.0.
Thanks.

**Comment by zimenglan-sysu-512** [comment]
@hszhao thanks

**Comment by saviogeorge** [comment]
Yes the above solution worked for me as well
