### ISSUE TITLE
MATLAB crashes using cityscapes trained model

### ISSUE THREAD

**Issue by uu-ujwalkumar06** [hszhao/PSPNet#43]
I have been trying to test pspnet101_VOC2012.caffemodel, pspnet101_cityscapes.caffemodel, and pspnet50_ADE20K.caffemodel with my set of input images of size 1280*600, Each time I run eval_all.m, matlab crashes with the error as show below
![screenshot from 2017-05-27 10-45-47](https://cloud.githubusercontent.com/assets/25631520/26521104/caa7ec86-42fd-11e7-8a8c-6de122425a66.png)
![screenshot from 2017-05-27 10-46-04](https://cloud.githubusercontent.com/assets/25631520/26521106/cd069e64-42fd-11e7-9c1c-8d431dabd23d.png)

I don't understand what the actual problem is, I am running it on a GPU with configuration
![screenshot from 2017-05-27 10-54-29](https://cloud.githubusercontent.com/assets/25631520/26521108/d5478a52-42fd-11e7-9a5e-fba141a2bf9c.png)

 have made my makefile.config with openmpi. 

On trying to run it with pspnet101_VOC2012.caffemodel with a sample of images I am able to run it without crashing, but the result saved in /home/PSPNet/evaluation/mc_result/VOC2012/test/pspnet101_473/color shows images with all pixel values 11.

Please let me know, What is wrong, and guide me to successfully test PSPNet with my data set.

**Comment by yugeshegala** [comment]
I too have the same issue, Please let me know asap

**Comment by qizhuli** [comment]
When you get the out-of-memory error, what model were you testing?

**Comment by uu-ujwalkumar06** [comment]
@qizhuli I get out of memory error for pspnet101_cityscapes.caffemodel, the other two models run without getting crashed, but the results show images with 11 in every pixel.

**Comment by uu-ujwalkumar06** [comment]
I am successfully able to run with out cudNN and get the results using ADEK and VOC2012 trained models. But while using cityscapes trained model, MATLAB crashes. Is there anything to be changed in the code, or is it the trained model that is affecting this case. Please let me know how do I solve this case.

**Comment by qizhuli** [comment]
@uu-ujwalkumar06 because cityscapes model has a larger input image size as compared to the VOC2012 model, your 8GB GPU memory is not enough for evaluating it.

**Comment by pewpewpeww** [comment]
Hi, can I ask if you managed to solve the issue of out of memory for CityScapes dataset evaluation? 

I currently have 2 x GTX 1080 8GB am I am facing out of memory issue. 

Would appreciate if you could enlighten me on this, thank you!!!
