### ISSUE TITLE
Evaluation with VOC2012

### ISSUE THREAD

**Issue by gopi77** [hszhao/PSPNet#48]
Hi As per step 3. evaluation, 
1. I downloaded VOC2012 dataset from http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar.
2. updated the path in eval_all.m. (inside /evaluation/samplelist)
3. I also used the existing VOC2012_test.txt
4. While running the ./run.sh, I got the below error.

-----------------------------
Starting parallel pool (parpool) using the 'local' profile ...
connected to 4 workers.
Error using importdata (line 137)
Unable to open file.

Error in eval_sub (line 3)
list = importdata(fullfile(data_root,eval_list));

Error in eval_all (line 71)
parfor i = 1:gpu_num %change 'parfor' to 'for' if singe GPU testing is used

-------------------------------

One thing I observed is whatever filenames mentioned in VOC2012_test.txt are missing inside path VOC2012/JPEGImages.

Ex: 
The first 5 lines of  VOC2012_test.txt file are
/JPEGImages/2008_000006.jpg
/JPEGImages/2008_000011.jpg
/JPEGImages/2008_000012.jpg
/JPEGImages/2008_000018.jpg
/JPEGImages/2008_000024.jpg

But the available files in VOC2012/JPEGImages are like
/JPEGImages/2008_000002.jpg
/JPEGImages/2008_000003.jpg
/JPEGImages/2008_000007.jpg
/JPEGImages/2008_000008.jpg
/JPEGImages/2008_000009.jpg

Why the filenames like 6, 11, 12, 18, 24, ... are missing inside VOC2012/JPEGImages is unclear.
Do I need to download VOC2012 from some other place?, please let me know.

FYI, I tried downloading ADE20K, but the folder structures are totally different & don't know how to modify ADE20K_val.txt (big manual work) & gave up.

**Comment by qizhuli** [comment]
You need to register an account on the VOC 2012 server, and download the test data (which contains all the test images) after you log in.

**Comment by gopi77** [comment]
Hi

Thanks for the comment.
I downloaded the test data & able to see the files.
Kept these file inside the folder evaluation. (Ex: /home/gopi/PSPNet/evaluation/VOC2012/JPEGImages/2008_000001.jpg)

Still I have the errors while running ./run.sh.

Attached my eval_all.m file for reference.


[eval_all.m.txt](https://github.com/hszhao/PSPNet/files/1128976/eval_all.m.txt)

**Comment by qizhuli** [comment]
The errror says it can't locate your `eval_list` file. 
According to your attached `eval_all.m `script, it is looking at relative path `VOC2012/samplelist/VOC2012_test.txt`. 
Make sure this exists in the directory where you run your `eval_all.m` script.

**Comment by gopi77** [comment]
Thanks, solved the path problem
Now facing another problem, will open a new issue

**Comment by zaheer789** [comment]
Help Please!

Hi As per step 3. evaluation

downloaded cityscapes dataset from https://drive.google.com/file/d/1z_2yifjYICczhZjBqCEhE1m6GYwJuljn/view

While running the ./run.sh, I got the below error

Error using importdata
Unable to open file.

Error in eval_sub (line 3)
list = importdata(fullfile(data_root,eval_list));

Error in eval_all (line 35)
eval_sub(data_name,data_root,eval_list,model_weights,model_deploy,fea_cha,crop_size_h,crop_size_w,data_class,data_colormap, ...

Please help
[eval_all.txt](https://github.com/hszhao/PSPNet/files/8778293/eval_all.txt)
