### ISSUE TITLE
.build_release/src/caffe/layers/densecrf_layer.o:无法识别文件: 文件被截断

### ISSUE THREAD

**Issue by lang25150** [hszhao/PSPNet#5]
There was a bug when I tried to make all. 
The details are as follows:

LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
.build_release/src/caffe/layers/densecrf_layer.o:无法识别文件: 文件被截断
collect2: 错误： ld 返回 1
Makefile:567: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

Could you help me about this problem?  Thank you!

Best wishes

**Comment by hszhao** [comment]
Hi, you may try 'make clean' and make again. If your server has build Caffe before, it should be OK. Thanks,
