### ISSUE TITLE
the shared model on voc

### ISSUE THREAD

**Issue by pkuCactus** [hszhao/PSPNet#64]
hello, the shared model on voc is whether pretrained on  MS-COCO or not, thanks to help

**Comment by qizhuli** [comment]
The released model gets 85.4 mIoU on VOC2012 test set. Therefore it should be their COCO-pretrained model according to the paper.

**Comment by pkuCactus** [comment]
but i got 83.54 mIoU on VOC2012 val set use the released model

**Comment by pkuCactus** [comment]
and i submit the result i got sue the model, only 84.59, this is the url http://host.robots.ox.ac.uk:8080/eval/view_submission/13080/

**Comment by qizhuli** [comment]
That is peculiar. I, too, tested their released VOC model using their evaluation code, and the [results](http://host.robots.ox.ac.uk:8080/anonymous/KK0XKZ.html) are exactly the same as what they reported in Table 6 of the paper for their COCO-pretrained model. 85.4 mIoU.

**Comment by qizhuli** [comment]
By the way, only you can access the link you provided as that is private to your account. For others to view the results, you should use the "Anonymous result link" :)

**Comment by pkuCactus** [comment]
thanks a lot, iguess i knew where i was wrong. maybe that i used only one scale when test, while it test on 6 scales
