### ISSUE TITLE
Anyone train the model successfully and achieve comparable performance

### ISSUE THREAD

**Issue by gaopeng-eugene** [hszhao/PSPNet#65]

**Comment by hellochick** [comment]
Hey @gaopeng-eugene , I reproduced the model using tensorflow, you can take a look on it:
https://github.com/hellochick/PSPNet_tensorflow

**Comment by zhanghang1989** [comment]
PSPNet-50 on PyTorch achieve 40% mIoU on ADE20K, code will be released later at http://hangzh.com/PyTorch-Encoding/  stay tuned.

**Comment by rohitgajawada** [comment]
@zhanghang1989 Hi, any update about when you would be releasing your code? Thank you very much :smiley:

**Comment by zhanghang1989** [comment]
Achieved using SyncBN. Code will be released soon with my coming paper

http://hangzh.com/PyTorch-Encoding/
https://github.com/zhanghang1989/PyTorch-Encoding
