### ISSUE TITLE
Define class (ColorMap) for my Data

### ISSUE THREAD

**Issue by ThienAnh** [hszhao/PSPNet#67]
Dear all.

I want to  training PSPNet with my data, so where and how can i define class (label) (Ex: Define color RGB(123,123,123) is for clother, RGB( 200,123,150) is for Desk.....).

Thanks so much.

**Comment by hellochick** [comment]
@ThienAnh , I think it's in PSPNet/evaluation/visualizationCode

**Comment by ThienAnh** [comment]
@hellochick in visualizationCode fodel is matlab code, i want to find ColorMap in python. :(

**Comment by hellochick** [comment]
@ThienAnh , I think you can use scipy.loadmat() to load 'objectName19.mat' and change color in that file

**Comment by ThienAnh** [comment]
@hellochick I understand. Thank you so much.

**Comment by ThienAnh** [comment]
Hi @hellochick 
I'm try to train with my data. But i don't know how create data for training.

In file train_aug.txt, only mapping between original image (JPEGImages/2007_000364.jpg) with contour image (/SegmentationClassAug/2007_000364.png) --> That seem all image in SegmentationClassAug folder is edge(contour). So how program can mapping color label for train?

Thanks

**Comment by pewpewpeww** [comment]
Hi @ThienAnh and @hellochick, did you manage to change the label correctly together with the colour label? If so, can you advice me so. I am currently trying to do this but i am facing some difficulty. 

When I open ObjectName19.mat I only see the object names. 

Thank you.

**Comment by ThienAnh** [comment]
@pewpewpeww  please give me your mail, i will send code c++ predict and mapping color with label for you

**Comment by pewpewpeww** [comment]
@ThienAnh Thank you for your prompt reply! You can email me at
sheryltoh97@gmail.com. Thank you so much.
